### ISSUE TITLE
As a user, I want to update the description of a document so that I can sort and find it better

### ISSUE THREAD

**Issue by jjohnson382** [cfeng46/HealthPort#15]
## Story/Task Details
- [ ] Create edit document button
- [ ] Create edit document page
- [ ] Update document description in database

## Acceptance Scenarios
- Given: The user is on the documents page
- When: The user clicks on a document
- Then: They see a preview of the document
- When: They click the edit button
- Then: They land on a page to edit document details
- When: They click save
- Then: The document is updated and they return to the document preview page
