### ISSUE TITLE
As a user, I want to find an existing document in my storage so that I can examine or share it

### ISSUE THREAD

**Issue by jjohnson382** [cfeng46/HealthPort#16]
## Story/Task Details
- [ ] Create documents search bar
- [ ] Filter documents by search bar input
- [ ] filter displayed document list

## Acceptance Scenarios
- Given: The user is on the documents page
- When: The user types letters into the document search bar
- Then: The user sees only documents that start with those letters in their document list
