### ISSUE TITLE
As a user, I want to remove a document so that my storage is minimal

### ISSUE THREAD

**Issue by jjohnson382** [cfeng46/HealthPort#17]
## Story/Task Details
- [ ] Create delete button on preview page
- [ ] delete document in database
- [ ] create confirmation dialog

## Acceptance Scenarios
- Given: The user is on the documents preview page
- When: The user hits the delete button
- Then: The user is taken to the document list, and the deleted document is no longer there
