### ISSUE TITLE
As a user, I want to change my registration information

### ISSUE THREAD

**Issue by cfeng46** [cfeng46/HealthPort#52]
## Story/Task Details
- [] Create settings page
- [] Create settings widge on home page
- [] Connect settings UI with schema for user information

## Acceptance Scenarios
see stories

**Comment by twalker61** [comment]
User information doesn't persist after logging out because functionality is not connected to the database.
