### ISSUE TITLE
As a user, I want to find a contact in my list so that I can examine or edit it

### ISSUE THREAD

**Issue by twalker61** [cfeng46/HealthPort#69]
## Story/Task Details
- [ ] Create contact search bar
- [ ] Filter contacts by search bar input
- [ ] filter contact list

## Acceptance Scenarios
- Given: The user is on the contacts page
- When: The user types letters into the contact bar
- Then: The user sees only contacts that start with those letters in their contact list
